### PR TITLE
Tag creation

### PR DESCRIPTION
**Pull request by zMarshello**
Integrating tag creation to expert tags component. Hits endpoint and updates in database

### CODE REVIEW

**Review by AdamDKing — CHANGES_REQUESTED** [review]
This needs to be finished -- remove console logs and provide feedback to the user that their tag was successfully or unsuccessfully created

**Comment by AdamDKing** [comment]
Kyung is working on "snackbar" for feedback to the user, we should be consistent and do the same here

**Comment by zMarshello** [comment]
Are you refering to something at the bottom of the screen thats pops up to tell the user success? I could add something in that displays a "snackbar" based on the response status code

Question:
- Would it be better to make a snackbar compenet that we can resuse? That way, if its successful, I can just pass a message to the snackbar component?

**Review by AdamDKing — APPROVED** [review]
Looks good

**Pull request merged**
